# Generated by Django 3.0 on 2020-05-01 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0002_car_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classic',
            fields=[
                ('car_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Sales.Car')),
            ],
            bases=('Sales.car',),
        ),
    ]
