# Generated by Django 3.0 on 2020-05-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0003_classic'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_classic',
            field=models.BooleanField(default=False),
        ),
    ]
